oOauth:
  client-id: ENC(iiKYNgoyNaQOttEPz+dqy8BVcDf7N9ardBMXHvdXS/mveV8wSLBKFAUi5fzUB+Xq8WLLjn+lPbgN2ngGUkHoeFYGl43UwWy7DI3DnNBCQ3B1+TUTf5XwcA==)
  client-secret: ENC(f0ghzB+1/bB28Kqsk0zi125xy6kMVCW5eGOBpfojoE0HB9M6RlZSYxMHoecq9x4P)
  scope: https://www.googleapis.com/auth/youtube.force-ssl
  provider:
    authorization-uri: https://accounts.google.com/o/oauth2/auth
    token-uri: https://accounts.google.com/o/oauth2/token
    user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    user-name-attribute: sub

logging:
  level:
    org:
      springframework:
        security: trace

spring:
  profiles:
    include: secret

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(iiKYNgoyNaQOttEPz+dqy8BVcDf7N9ardBMXHvdXS/mveV8wSLBKFAUi5fzUB+Xq8WLLjn+lPbgN2ngGUkHoeFYGl43UwWy7DI3DnNBCQ3B1+TUTf5XwcA==)
            client-secret: ENC(f0ghzB+1/bB28Kqsk0zi125xy6kMVCW5eGOBpfojoE0HB9M6RlZSYxMHoecq9x4P)
            scope:
              - https://www.googleapis.com/auth/youtube.force-ssl
            redirect-uri: http://localhost:8080/callback
#    user:
#      name: user
#      password: 0000